setono_sylius_feed_shop_feed_show:
    path: /feed/{slug}
    methods: [GET]
    defaults:
        _controller: setono_sylius_feed.controller.action.show_feed
        _sylius:
            repository:
                method: findOneBySlug
                arguments:
                    - $slug
