sylius_grid:
    grids:
        loevgaard_sylius_feed_admin_feed:
            driver:
                name: doctrine/orm
                options:
                    class: Loevgaard\SyliusFeedPlugin\Entity\Feed
            fields:
                name:
                    type: string
                    label: loevgaard_sylius_feed.ui.name
                slug:
                    type: string
                    label: loevgaard_sylius_feed.ui.slug
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete