sylius_resource:
    resources:
        loevgaard_sylius_feed.feed:
            driver: doctrine/orm
            classes:
                model: Loevgaard\SyliusFeedPlugin\Entity\Feed
                interface: Loevgaard\SyliusFeedPlugin\Entity\FeedInterface
                repository: Loevgaard\SyliusFeedPlugin\Repository\FeedRepository
                controller: Loevgaard\SyliusFeedPlugin\Controller\FeedController

sylius_grid:
    grids:
        loevgaard_sylius_feed_admin_feed:
            driver:
                name: doctrine/orm
                options:
                    class: Loevgaard\SyliusFeedPlugin\Entity\Feed
            fields:
                name:
                    type: string
                    label: loevgaard_sylius_feed.ui.name
                slug:
                    type: string
                    label: loevgaard_sylius_feed.ui.slug
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete