services:
    loevgaard_sylius_feed.listener.admin.menu_builder:
        class: Loevgaard\SyliusFeedPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }